#Storing variables and inputting a value
print("In this story, we need 4 names of 4 trees.")
name1 = input("Give us a name for the 1st tree: ")
name1 = name1.capitalize()
name2 = input("Give us a name for the 2nd tree: ")
name2 = name2.capitalize()
name3 = input("Give us a name for the 3rd tree: ")
name3 = name3.capitalize()
name4 = input("Give us a name for the 4th tree: ")
name4 = name4.capitalize()
#Displaying all four names
print("\nThe names we have are " + name1 + ", " + name2 + ", " + name3 + ", and " + name4 + ".")
print(input("\nLoading to make our story. Please Press enter!"))
#Displaying the story
title = "the four trees"
title = title.upper()
print(input("The title of our story is " + title + ". \nPlease press enter to read the story."))
print("\nOnce upon a time in a land not too far away,")
#Added input statement and press enter to make the story readable
print(input("four trees, named " + name1 + ", " + name2 + ", " + name3 + ", and " + name4 + " started to grow on top of a small hill.\t Press enter!"))
print("Three of the trees are very selfish,")
print("arrogant, and proud trees always boasting")
print("how big and tall they will become, teasing")
print(input("each other how they will live forever.\t Press enter!"))
print("The fourth tree, "+name4+" is all happy and")
print(input("content, just to be a tree.\t Press enter!"))
print("As time passes the three proud and")
print("selfish trees spend all their days growing")
print("as tall and impressive as they can,")
print("boasting each and everyday how")
print(input("wonderful they will be.\t Press enter!"))
print(name4+" listens but is all happy")
print("and content, just to be a tree.")
print(input("\nPress enter!"))
print("The End!")